package com.capo.diarioclase.ui.capture
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.capo.diarioclase.data.db.*
import com.capo.diarioclase.data.repository.SessionRepository
import com.capo.diarioclase.processing.evidence.*
import com.capo.diarioclase.processing.transcription.SpanishModelDownloadState
import com.capo.diarioclase.processing.work.ProcessingOutcome
import com.capo.diarioclase.diary.cleanup.CleanupOutcome
import com.capo.diarioclase.diary.DiaryEntry
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.*
import java.util.concurrent.atomic.AtomicBoolean
interface CaptureActions { suspend fun startNewDay();suspend fun resume(id:SessionId);suspend fun pause();suspend fun markHomework(sessionId:SessionId,blockId:BlockId);suspend fun finalizeDay(id:SessionId,state:SessionState);suspend fun process(id:SessionId,mode:InterpretationMode):ProcessingOutcome=error("Procesamiento no configurado");suspend fun requestLanguageModel(onUpdate:(SpanishModelDownloadState)->Unit={}):SpanishModelDownloadState=SpanishModelDownloadState.Unsupported;suspend fun saveDraft(draft:DiaryDraftEntity){};suspend fun approveAndClean(draft:DiaryDraftEntity):CleanupOutcome=error("Aprobación no configurada");suspend fun retryCleanup(sessionId:SessionId):CleanupOutcome=error("Limpieza no configurada") }
class CaptureViewModel(repository:SessionRepository,private val actions:CaptureActions,scope:CoroutineScope?=null,drafts:Flow<DiaryDraftEntity?> = flowOf(null),claims:Flow<List<EvidenceClaim>> = flowOf(emptyList()),pendingRecordings:Flow<RecordingReport?> = repository.observeLatestCleanupPendingRecording(),diaries:Flow<List<DiaryEntry>> = flowOf(emptyList())):ViewModel(){
 private val workScope=scope?:viewModelScope;private val _state=MutableStateFlow(CaptureUiState());val state:StateFlow<CaptureUiState> = _state.asStateFlow();private val actionInProgress=AtomicBoolean(false)
 init {workScope.launch{combine(repository.observeActiveSession().map{it as Any?},repository.observeLatestFinalizedRecording().map{it as Any?},drafts.map{it as Any?},claims.map{it as Any?},pendingRecordings.map{it as Any?},diaries.map{it as Any?}){values->values}.collect{values->
  val session=values[0] as SessionAggregate?;val report=values[1] as RecordingReport?;val draft=values[2] as DiaryDraftEntity?;@Suppress("UNCHECKED_CAST") val evidence=values[3] as List<EvidenceClaim>;val pending=values[4] as RecordingReport?;@Suppress("UNCHECKED_CAST") val entries=values[5] as List<DiaryEntry>
  if(_state.value.status in setOf(CaptureStatus.APPROVING,CaptureStatus.ARCHIVED)&&!(_state.value.status==CaptureStatus.ARCHIVED&&session!=null)) return@collect
  if(_state.value.status==CaptureStatus.CLEANUP_PENDING&&pending==null) return@collect
  _state.value=session?.let{CaptureUiState(if(it.state==SessionState.RECORDING)CaptureStatus.RECORDING else CaptureStatus.PAUSED,it.id,it.blocks.lastOrNull(),it.blocks.size,it.durationMs,_state.value.homeworkMarkers,false,"Los bloques cerrados están guardados",report,draft,evidence) }?:pending?.let{pendingReport->val entry=entries.firstOrNull{it.sessionId==pendingReport.sessionId};CaptureUiState(CaptureStatus.CLEANUP_PENDING,pendingReport.sessionId,message="La ficha permanente está segura. La limpieza temporal requiere reintento",lastRecording=pendingReport,draft=entry?.toRecoveredDraft(),diaryId=entry?.id)}?:report?.let{
   val failed=it.segments.any{s->s.state==SegmentState.FAILED};val status=when{it.state==SessionState.AWAITING_REVIEW&&draft!=null->CaptureStatus.DRAFT;it.state in setOf(SessionState.TRANSCRIBING,SessionState.EXTRACTING)&&!failed->CaptureStatus.PROCESSING;else->CaptureStatus.REVIEW}
   val storedFailure=it.segments.firstOrNull{s->s.state==SegmentState.FAILED}?.lastTranscriptionFailure?.let{code->runCatching{com.capo.diarioclase.processing.transcription.TranscriptionFailure.valueOf(code)}.getOrNull()}
   CaptureUiState(status=status,sessionId=it.sessionId,busy=actionInProgress.get()||status==CaptureStatus.PROCESSING,message=when{failed->storedFailure?.let(::failureMessage)?:"Falló un segmento. El audio sigue guardado y podés reintentar";status==CaptureStatus.PROCESSING->"Procesando los segmentos guardados";status==CaptureStatus.DRAFT->"Ficha generada. Revisá antes de aprobar";else->if(it.allAudioReady)"Audio verificado y disponible" else "Revisá el estado del audio"},lastRecording=it,draft=draft,claims=evidence)
  }?:CaptureUiState()
 }};workScope.launch{while(isActive){delay(1_000);if(_state.value.status==CaptureStatus.RECORDING)_state.update{it.copy(totalDurationMs=it.totalDurationMs+1_000)}}}}
 fun onStart(){execute{actions.startNewDay()}};fun onResume(){_state.value.sessionId?.let{id->execute{actions.resume(id)}}};fun onPause(){execute{actions.pause()}}
 fun onMarkHomework(){val s=_state.value.sessionId;val b=_state.value.currentBlockId;if(s!=null&&b!=null)execute(clearOnSuccess=true){actions.markHomework(s,b);_state.update{it.copy(homeworkMarkers=it.homeworkMarkers+1,message="Tarea marcada")}}}
 fun onFinalize(){val s=_state.value;val id=s.sessionId?:return;execute{actions.finalizeDay(id,if(s.status==CaptureStatus.RECORDING)SessionState.RECORDING else SessionState.PAUSED)}}
 fun onProcess(mode:InterpretationMode=InterpretationMode.CONSERVATIVE){val id=_state.value.lastRecording?.sessionId?:return;execute(clearOnSuccess=true){processAndShow(id,mode)}}
 fun onMode(mode:InterpretationMode,topics:String,activities:String,pages:String,exercises:String,homework:String){val draft=_state.value.draft?:return;execute(clearOnSuccess=true){actions.saveDraft(draft.copy(topics=topics,activities=activities,pages=pages,exercises=exercises,homework=homework,userEdited=true));processAndShow(SessionId(draft.sessionId),mode)}}
 private suspend fun processAndShow(id:SessionId,mode:InterpretationMode){when(val outcome=actions.process(id,mode)){is ProcessingOutcome.Complete->_state.update{it.copy(busy=false,message="Ficha generada")};is ProcessingOutcome.Failed->_state.update{it.copy(busy=false,message=failureMessage(outcome.failure))}}}
 fun onRequestModel(){execute(clearOnSuccess=true){applyModelDownloadState(SpanishModelDownloadState.Checking);val result=try{actions.requestLanguageModel(::applyModelDownloadState)}catch(error:CancellationException){throw error}catch(error:Exception){throw IllegalStateException("No se pudo comprobar el idioma local en este teléfono",error)};applyModelDownloadState(result)}}
 fun onSaveDraft(topics:String,activities:String,pages:String,exercises:String,homework:String){val draft=_state.value.draft?:return;execute(clearOnSuccess=true){actions.saveDraft(draft.copy(topics=topics,activities=activities,pages=pages,exercises=exercises,homework=homework));_state.update{it.copy(message="Cambios guardados")}}}
 fun onApprove(topics:String,activities:String,pages:String,exercises:String,homework:String){val current=_state.value;val draft=current.draft?:return;if(current.busy||current.status!=CaptureStatus.DRAFT)return;val edited=draft.copy(topics=topics,activities=activities,pages=pages,exercises=exercises,homework=homework,userEdited=true);_state.value=current.copy(status=CaptureStatus.APPROVING,busy=true,message="Guardando la ficha permanente",draft=edited);workScope.launch{try{showApprovalOutcome(actions.approveAndClean(edited))}catch(error:CancellationException){throw error}catch(error:Exception){_state.update{it.copy(status=CaptureStatus.DRAFT,busy=false,message=error.message?:"No se pudo aprobar la ficha")}}}}
 fun onRetryCleanup(){val current=_state.value;val sessionId=current.sessionId?:return;if(current.busy||current.status!=CaptureStatus.CLEANUP_PENDING)return;_state.value=current.copy(status=CaptureStatus.APPROVING,busy=true,message="Reintentando la limpieza");workScope.launch{try{showRetryOutcome(actions.retryCleanup(sessionId))}catch(error:CancellationException){throw error}catch(error:Exception){_state.update{it.copy(status=CaptureStatus.CLEANUP_PENDING,busy=false,message="La ficha permanente sigue segura. ${error.message?:"No se pudo reintentar la limpieza"}")}}}}
 private fun showApprovalOutcome(outcome:CleanupOutcome)=showCleanupOutcome(outcome,CaptureStatus.DRAFT)
 private fun showRetryOutcome(outcome:CleanupOutcome)=showCleanupOutcome(outcome,CaptureStatus.CLEANUP_PENDING)
 private fun showCleanupOutcome(outcome:CleanupOutcome,saveFailureStatus:CaptureStatus){_state.update{current->when(outcome){is CleanupOutcome.Archived->current.copy(status=CaptureStatus.ARCHIVED,busy=false,diaryId=outcome.diaryId,message="Diario archivado y temporales eliminados");is CleanupOutcome.Pending->current.copy(status=CaptureStatus.CLEANUP_PENDING,busy=false,diaryId=outcome.diaryId,message="La ficha está segura. La limpieza temporal requiere reintento");is CleanupOutcome.SaveFailed->current.copy(status=saveFailureStatus,busy=false,message=if(saveFailureStatus==CaptureStatus.CLEANUP_PENDING)"La ficha permanente sigue segura. ${outcome.reason}" else outcome.reason)}}}
 private fun failureMessage(failure:com.capo.diarioclase.processing.transcription.TranscriptionFailure)=when(failure){com.capo.diarioclase.processing.transcription.TranscriptionFailure.ON_DEVICE_UNAVAILABLE->"Este teléfono no ofrece transcripción local";com.capo.diarioclase.processing.transcription.TranscriptionFailure.LANGUAGE_UNAVAILABLE->"Falta el modelo local de español";com.capo.diarioclase.processing.transcription.TranscriptionFailure.AUDIO_SOURCE_UNSUPPORTED->"Este teléfono no admite desgrabar el audio guardado con el motor local. El audio sigue seguro";com.capo.diarioclase.processing.transcription.TranscriptionFailure.NO_SPEECH->"No se detectó voz. El audio sigue guardado";com.capo.diarioclase.processing.transcription.TranscriptionFailure.RECOGNIZER_BUSY->"El transcriptor está ocupado. Reintentá";com.capo.diarioclase.processing.transcription.TranscriptionFailure.INVALID_AUDIO->"Un segmento de audio no es válido";com.capo.diarioclase.processing.transcription.TranscriptionFailure.TIMEOUT->"La transcripción local no respondió a tiempo. El audio sigue guardado";else->"La transcripción falló. El audio sigue guardado"}
 private fun applyModelDownloadState(model:SpanishModelDownloadState){_state.update{it.copy(modelDownload=model,message=when(model){SpanishModelDownloadState.Checking->"Comprobando modelos locales de español";is SpanishModelDownloadState.Downloading->"Descargando español ${model.languageTag}: ${model.completedPercent}%";is SpanishModelDownloadState.Scheduled->"Descarga de español programada por Android. Todavía no está lista";is SpanishModelDownloadState.Ready->"Español local listo (${model.languageTag}). Ya podés reintentar";SpanishModelDownloadState.Unsupported->"Este teléfono no ofrece ningún modelo local de español";is SpanishModelDownloadState.Failed->"Android rechazó la descarga del español (código ${model.errorCode})"}}}
 private fun execute(clearOnSuccess:Boolean=false,action:suspend()->Unit){if(_state.value.busy||!actionInProgress.compareAndSet(false,true))return;_state.update{it.copy(busy=true,message=null)};workScope.launch{try{action();if(clearOnSuccess)_state.update{it.copy(busy=false)}}catch(error:CancellationException){throw error}catch(error:Exception){_state.update{it.copy(busy=false,message=error.message)}}finally{actionInProgress.set(false);_state.update{it.copy(busy=false)}}}}
 private fun DiaryEntry.toRecoveredDraft()=DiaryDraftEntity("permanent-$id",sessionId.value,InterpretationMode.CONSERVATIVE.name,topics,activities,pages,completedExercises,homework,updatedAtEpochMs,userEdited=true)
}
